const { chromium } = require('playwright-core');
const http = require('http'), fs = require('fs'), path = require('path');
const ROOT = 'C:/Users/ADMIN/projects/dance-project', Y4M = path.join(__dirname, 'fakecam.y4m');
const MIME = { '.html':'text/html','.js':'text/javascript','.mp4':'video/mp4','.png':'image/png','.riv':'application/octet-stream','.css':'text/css','.mp3':'audio/mpeg' };
(async () => {
  const server = http.createServer((q, r) => { let p = decodeURIComponent(q.url.split('?')[0]); if (p === '/') p = '/nova-joined.html';
    fs.readFile(path.join(ROOT, p), (e, d) => { if (e) { r.writeHead(404); r.end(); return; } r.writeHead(200, { 'Content-Type': MIME[path.extname(p).toLowerCase()] || 'application/octet-stream' }); r.end(d); }); });
  await new Promise(r => server.listen(0, r)); const port = server.address().port;
  const b = await chromium.launch({ channel: 'chrome', headless: true, args: ['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream','--use-file-for-fake-video-capture=' + Y4M,'--autoplay-policy=no-user-gesture-required','--enable-unsafe-swiftshader'] });
  const ctx = await b.newContext({ permissions: ['camera','microphone'] });
  const pg = await ctx.newPage();
  const errs = []; pg.on('pageerror', e => errs.push(e.message));
  await pg.goto(`http://localhost:${port}/nova-joined.html`, { waitUntil: 'domcontentloaded' });
  await pg.waitForTimeout(2500);
  const d1 = await pg.evaluate(() => ({ memType: typeof memory, btn: !!document.getElementById('arrival-start-btn'), tap: typeof onArrivalTap }));
  console.log('pre-tap:', JSON.stringify(d1), 'pageerrors:', JSON.stringify(errs));
  await pg.click('#arrival-start-btn', { force: true }).catch(e => console.log('click err', e.message));
  await pg.waitForTimeout(3000);
  const d2 = await pg.evaluate(() => ({ memType: typeof memory, phase: (typeof memory!=='undefined') ? memory.phase : null, rec: !!document.getElementById('phase-recognition') }));
  console.log('post-tap:', JSON.stringify(d2), 'pageerrors:', JSON.stringify(errs));
  await b.close(); server.close();
})();
